# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.provision "shell", path: "install.sh"
    config.vm.network "private_network", ip: "192.168.56.10"
    # add 192.168.56.10 chat.localhost.io to your host file
    config.vm.provider "virtualbox" do |v|
      v.name = "matrixSynapse"
      v.memory = 8192
      v.cpus = 2
    end
  end